services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin-by-compose
    #user: 1000:1000
    volumes:
      - /home/shohel/mygithub/docker-project/Jellyfin-Compose/config:/config
      - /home/shohel/mygithub/docker-project/Jellyfin-Compose/cache:/cache
      - type: bind
        source: /home/shohel/mygithub/docker-project/Jellyfin-Compose/media
        target: /media
        read_only: true
    ports:
      - 8097:8096/tcp
    restart: 'unless-stopped'